
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1235, 609)

        # Create a horizontal layout widget for the buttons
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 10, 161, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Create an "Upload File" button
        self.UploadFile = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.UploadFile.setEnabled(True)
        self.UploadFile.setMaximumSize(QtCore.QSize(140, 90))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.UploadFile.setFont(font)
        self.UploadFile.setObjectName("UploadFile")
        self.horizontalLayout.addWidget(self.UploadFile)

        # Create a grid layout widget for displaying data
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 70, 721, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")

        # Create a scroll area for displaying data
        self.showData = QtWidgets.QScrollArea(parent=self.gridLayoutWidget)
        self.showData.setWidgetResizable(True)
        self.showData.setObjectName("showData")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 717, 237))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ShowData = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.ShowData.setGeometry(QtCore.QRect(0, 0, 721, 241))
        self.ShowData.setObjectName("ShowData")
        self.showData.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.showData, 0, 0, 1, 1)

        # Create another grid layout widget for describing data
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 350, 721, 241))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # Create a scroll area for describing data
        self.desc_data = QtWidgets.QScrollArea(parent=self.gridLayoutWidget_2)
        self.desc_data.setWidgetResizable(True)
        self.desc_data.setObjectName("descibe data")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 717, 237))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Datadesc = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.Datadesc.setGeometry(QtCore.QRect(0, 0, 721, 241))
        self.Datadesc.setObjectName("Data description")
        self.desc_data.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.desc_data, 0, 0, 1, 1)

        # Create a vertical slider
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(850, 40, 131, 35))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label= QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(850, 150, 131, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")

        #ِCreate A widget for the MSE , MAE , RMSE
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)

        # GrouBBOX For choosing the MSE , MAE , RMSE
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(920, 260, 141, 151))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.MSE = QtWidgets.QRadioButton(parent=self.groupBox)
        self.MSE.setEnabled(False)
        self.MSE.setGeometry(QtCore.QRect(10, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.MSE.setFont(font)
        self.MSE.setObjectName("MSE")
        self.MAE = QtWidgets.QRadioButton(parent=self.groupBox)
        self.MAE.setEnabled(False)
        self.MAE.setGeometry(QtCore.QRect(10, 70, 95, 20))
        self.MAE.setObjectName("MAE")
        self.MAE.setFont(font)
        self.RMSE = QtWidgets.QRadioButton(parent=self.groupBox)
        self.RMSE.setEnabled(False)
        self.RMSE.setGeometry(QtCore.QRect(10, 110, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.RMSE.setFont(font)
        self.RMSE.setObjectName("RMSE")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(790, 430, 101, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")

        #CREATE a widget for Displaying the Train value
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.train = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.train.setEnabled(False)
        self.train.setObjectName("train")
        self.horizontalLayout_7.addWidget(self.train)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(790, 520, 101, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")

        #Create a widget for the  test values
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.test = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.test.setEnabled(False)
        self.test.setObjectName("test")
        self.horizontalLayout_8.addWidget(self.test)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(910, 430, 258, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.train_error = QtWidgets.QPlainTextEdit(parent=self.horizontalLayoutWidget_8)
        self.train_error.setEnabled(False)
        self.train_error.setObjectName("train_error")
        self.horizontalLayout_9.addWidget(self.train_error)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(910, 520, 260, 75))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)

        # self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.test_error = QtWidgets.QPlainTextEdit(parent=self.horizontalLayoutWidget_9)
        self.test_error.setEnabled(False)
        self.test_error.setObjectName("test_error")
        self.horizontalLayout_10.addWidget(self.test_error)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(850, 80, 241, 75))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)

        #a SLider for the test size
        self.verticalLayout.setObjectName("verticalLayout")
        self.testSize = QtWidgets.QSlider(parent=self.verticalLayoutWidget)
        self.testSize.setEnabled(False)
        self.testSize.setMaximum(99)
        self.testSize.setProperty("value", 0)
        self.testSize.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.testSize.setObjectName("testSize")
        self.verticalLayout.addWidget(self.testSize)
        self.testLb = QtWidgets.QLabel(parent=Dialog)
        self.testLb.setGeometry(QtCore.QRect(1060, 50, 49, 16))
        self.testLb.setObjectName("testLb")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(1000, 50, 49, 16))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(850, 190, 241, 46))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)

        #slider for the alpha size
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.alphaSize = QtWidgets.QSlider(parent=self.verticalLayoutWidget_2)
        self.alphaSize.setEnabled(False)
        self.alphaSize.setMaximum(99)
        self.alphaSize.setProperty("value", 0)
        self.alphaSize.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.alphaSize.setObjectName("alphaSize")
        self.verticalLayout_2.addWidget(self.alphaSize)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(1000, 160, 49, 16))
        self.label_4.setObjectName("label_4")
        self.alphaLb = QtWidgets.QLabel(parent=Dialog)
        self.alphaLb.setGeometry(QtCore.QRect(1060, 160, 49, 16))
        self.alphaLb.setObjectName("alphaLb")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    #Create Retranslate method to translate the ui elements
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.UploadFile.setText(_translate("Dialog", "Upload File"))
        self.UploadFile.setShortcut(_translate("Dialog", "Space"))
        self.label.setText(_translate("Dialog", "Size Test"))
        self.label_3.setText(_translate("Dialog", "Alpha Size"))
        self.MSE.setText(_translate("Dialog", "MSE"))
        self.MAE.setText(_translate("Dialog", "MAE"))
        self.RMSE.setText(_translate("Dialog", "RMSE"))
        self.train.setText(_translate("Dialog", "Train"))
        self.test.setText(_translate("Dialog", "Test"))
        self.testLb.setText(_translate("Dialog", "0"))
        self.label_2.setText(_translate("Dialog", "Value :"))
        self.label_4.setText(_translate("Dialog", "Value :"))
        self.alphaLb.setText(_translate("Dialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
